site_name: Eugene Yujun FU
site_description: Academic Profile of Dr. Eugene Yujun FU
site_author: Eugene Yujun FU

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:eugenefu@eduhk.hk
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=dipVCTIAAAAJ&hl=en
    - icon: fontawesome/brands/github
      link: https://github.com/AffectiveComputingLab-HK
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Eugene-Fu
